name: CI

env:
  FLUTTER_VERSION: '3.3.3'

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
